name: LaravelNeuro CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Choose the PHP version compatible with your package
        coverage: xdebug
        extensions: mbstring, xml, opcache, pdo_mysql, mbstring, exif, bcmath, xml, curl, gd, zip, intl # Add the extensions your package requires
        tools: composer, phpunit # Tools to install

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Add Testing Permissions
      run: chmod +x vendor/bin/phpunit

    - name: Run Tests
      run: vendor/bin/phpunit
